server {
  listen 80;
  server_name _;

  location / {
    root /app/dist/odds-worklog;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
  
  location /api/ {
    proxy_pass http://api:8080/;
  }
}
